spring:
  application:
    name: moa
  config:
    import:
      - moa-secret/oauth.yml
      - moa-secret/jwt.yml
      - moa-secret/db.yml
      - moa-secret/admin.yml
      - moa-secret/discord.yml
  servlet:
    multipart:
      enabled: false
  profiles:
    default: local

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

app:
  version: ${APP_VERSION:dev}
  deploy-color: ${DEPLOY_COLOR:local}
