spring:
  config:
    import:
      - moa-secret/oauth.yml
      - moa-secret/jwt.yml
      - moa-secret/db.yml
      - moa-secret/admin.yml
      - moa-secret/discord.yml
  servlet:
    multipart:
      enabled: false
  profiles:
    default: local

app:
  version: ${APP_VERSION:dev}
  deploy-color: ${DEPLOY_COLOR:local}
